Iter13
DenisKhanov/shorterURL pull request #17
Opened 2023-11-13 15:19 UTC by DenisKhanov

2023-11-14 06:07 UTC, edylcrm requested changes

2023-11-14 06:07 UTC, edylcrm commented on internal/app/repositoryes/dbstore.go
> +func (d *URLInDBRepo) StoreURLInDB(originalURL, shortURL string) error {
[BLOCKER] здесь лучше изменить сигнатуру метода на `StoreURLInDB(ctx context.Context, originalURL, shortURL string) error`. Каждый новый запрос будет создавать новый context, его можно получить обычно из request, но в зависимости от роутера может быть по разному. Этот пользовательский context может отмениться, допустим пользователь закрыл страницу браузера. В этом случае уже не надо делать запрос в БД и сам драйвер БД отменит запрос

2023-11-14 06:07 UTC, edylcrm commented on internal/app/repositoryes/dbstore.go
> +func (d *URLInDBRepo) StoreBatchURLInDB(batchURLtoStores map[string]string) error {
[BLOCKER] `StoreBatchURLInDB(ctx context.Context, batchURLtoStores map[string]string) error`

2023-11-14 06:07 UTC, edylcrm commented on internal/app/repositoryes/dbstore.go
> +func (d *URLInDBRepo) GetOriginalURLFromDB(shortURL string) (string, error) {
[BLOCKER] `GetOriginalURLFromDB(ctx context.Context, shortURL string) (string, error)`

2023-11-14 06:07 UTC, edylcrm commented on internal/app/repositoryes/dbstore.go
> +func (d *URLInDBRepo) GetShortURLFromDB(originalURL string) (string, error) {
[BLOCKER] `GetShortURLFromDB(ctx context.Context, originalURL string) (string, error)

2023-11-14 06:07 UTC, edylcrm commented on internal/app/repositoryes/dbstore.go
> +func (d *URLInDBRepo) GetShortBatchURLFromDB(batchURLRequests []models.URLRequest) (map[string]string, error) {
[BLOCKER] GetShortBatchURLFromDB(ctx context.Context, batchURLRequests []models.URLRequest) (map[string]string, error)

2023-11-16 08:37 UTC, edylcrm approved these changes

2023-11-19 11:29 UTC, merged

2023-11-20 20:03 UTC, Sovianum commented on internal/app/config/config.go
> +	flag.StringVar(&cfg.EnvDataBase, "d", "", "Set connect DB config")
А почему имена такие однобуквенные? Потом очень трудно угадать, что они значат. Плюс, мне кажется, логично было бы имена переменных тут сделать идентичными тегам полей
https://github.com/DenisKhanov/shorterURL/pull/17/files#diff-0a992a92ca1d92d5bbbed21fde4c70bc87c7e80ec0cc143f47064af01b36bd37R12-R16

2023-11-20 20:03 UTC, Sovianum commented on internal/app/config/config.go
> +		logrus.Fatal(err)
Имхо, тут не самое лучшее место для падения - может, на уровне main'а ты бы хотел как-то по-иначе ошибку обработать. Мне кажется, стоит эту ошибку явно навер прокинуть.

2023-11-20 20:03 UTC, Sovianum commented on internal/app/config/config_test.go
> +			flagArgs: []string{},
Это, кстати, не обязательно. nil-слайс - это во всех смыслах валидный объект, с которым можно делать все те же операции, что и с не-nil слайсом.

2023-11-20 20:03 UTC, Sovianum commented on internal/app/handlers/handlers.go
> +	GetBatchJSONShortURL(ctx context.Context, batchURLRequests []models.URLRequest) ([]models.URLResponse, error)
К этому методу у меня есть несколько вопросов:

Почему JSON фигурирует в названии метода? То, что у URLResponse есть json-тэги, - это деталь реализации, которая не должна влиять на сигнатуру метода.

Раз уж у тебя так и так есть `correlation_id`, то, может, на выходе возвращать мапу `map[string]models.URLResponse`? Кстати, еще круче было бы ввести для `correlation_id` отдельный тип, чтобы голые строки в сигнатурах не светились. 
Почему это лучше:
1. Снимается вопрос "должна ли длина ответа быть равна длине запроса" - не должна.
2. Должны ли айтемы в ответе идти в том же порядке, как и в запросе - не должны.
Ну, и по факту, тебе все равно на вызывающей стороне придется в мапу слайс перегонять, так как параллельное итерирование по двум массивам - это очень опасная идея)

2023-11-20 20:03 UTC, Sovianum commented on internal/app/handlers/handlers.go
> +	linc, err := c.GetRawData()
lin**k**

2023-11-20 20:03 UTC, Sovianum commented on internal/app/handlers/handlers.go
> +			c.String(http.StatusConflict, shortURL)
А разве эта ошибка вообще может вылететь из GetShortURL?

2023-11-20 20:03 UTC, Sovianum commented on internal/app/handlers/handlers.go
> +		c.Status(http.StatusBadRequest)
Ну, хз) Мне кажется, тут может быть разное - в том числе и ServerError. Стоит сюда добавить логирование.

2023-11-20 20:03 UTC, Sovianum commented on internal/app/handlers/handlers.go
> +		if err := h.DB.Ping(context.Background()); err != nil {
А почему тут бэкграунд, а не контекст запроса?

2023-11-20 20:03 UTC, Sovianum commented on internal/app/handlers/handlers.go
> +		c.Status(http.StatusOK)
То есть мы отдаем 200 независимо от того, произошла ли ошибка?

2023-11-20 20:03 UTC, Sovianum commented on internal/app/models/model.go
> +}
Вот я бы добавил 
```
type CorrelationID string
```

2023-11-20 20:03 UTC, Sovianum commented on internal/app/repositoryes/dbstore.go
> +	DB          *pgxpool.Pool //opened in main func DB pool connections
Эээээ... А почему ссылка на базу хранится прямо в сохраняемой сущности? Такого стоит максимально избегать по следующим причинам:
1. Права на работу с базой расползаются по коду, и кто-угодно может начать писать в нее какой-нибудь хлам.
2. Саму сущность, которая должна просто носить данные, становится труднее создать - для этого требуется коннектор для вполне конкретной базы. А если надо, например, положить эти данные в редис, то и еще один коннектор понадобится.

2023-11-20 20:03 UTC, Sovianum commented on internal/app/repositoryes/dbstore.go
repositories

2023-11-20 20:03 UTC, Sovianum commented on internal/app/repositoryes/dbstore.go
> +	return storage
Вот да, такое делать не надо) Коннектор до базы должен быть изолирован в рамках какого-то класса, который полностью им владеет. А модельки данных он может либо получать на вход, либо выдавать на выход.

2023-11-20 20:03 UTC, Sovianum commented on internal/app/repositoryes/dbstore.go
> +		logrus.Panicf("don't create table shortedurl: %v", err)
А почему паника? Почему бы просто не вернуть ошибку наверх?

2023-11-20 20:03 UTC, Sovianum commented on internal/app/repositoryes/dbstore.go
> +		logrus.Error("url don't save in database ", err)
О, а тут паники уже нет...

2023-11-20 20:03 UTC, Sovianum commented on internal/app/repositoryes/dbstore.go
> +	fmt.Println(2)
Это какие-то обломки отладки?

2023-11-20 20:03 UTC, Sovianum commented on internal/app/repositoryes/repository.go
> +	saveCtx, cancel := context.WithTimeout(context.Background(), time.Minute)
А почему background, а не тот контекст, который в параметрах пришел?

2023-11-20 20:03 UTC, Sovianum commented on internal/app/repositoryes/repository.go
> +			fmt.Println("Error saving to memory")
Тут стоит logrus заиспользовать.

2023-11-20 20:03 UTC, Sovianum commented on internal/app/services/service.go
> +	fmt.Println("Service GetBatchJSONShortURL run")
Это какой-то обломок отладки?

2023-11-20 20:03 UTC, Sovianum commented on internal/app/services/service.go
> +	var batchURLResponses []models.URLResponse
Это стоит перенести поближе к месту использования.

2023-11-20 20:03 UTC, Sovianum commented on internal/app/services/service.go
> +			batchURLResponses = append(batchURLResponses, models.URLResponse{CorrelationID: value.CorrelationID, ShortURL: s.baseURL + "/" + shortURL})
`s.baseURL + "/" + shortURL`. Для этого лучше использовать что-то типа path.Join

2023-11-20 20:03 UTC, Sovianum commented on internal/app/services/service.go
> +	saveCtx, cancel := context.WithTimeout(context.Background(), time.Minute)
Стоит использовать контекст из параметров

2023-11-20 20:03 UTC, Sovianum commented on cmd/shortener/main.go
> +	//router.Use(gzip.Gzip(gzip.BestSpeed))
Нужно удалить?

2023-11-21 13:41 UTC, DenisKhanov commented on internal/app/config/config.go
> +	flag.StringVar(&cfg.EnvDataBase, "d", "", "Set connect DB config")
Назфвание фдагов у нас по заданию такие прописывались, не упадут ли автотесты если я их изменю🤔

2023-11-22 13:39 UTC, DenisKhanov commented on internal/app/handlers/handlers.go
> +			c.String(http.StatusConflict, shortURL)
Было условие в задаче, выводить статус конфликт в ситуации, когда урл уже есть в базе, поэтому я в сервисе создаю ошибку и прокидываю ее в хендлер, чтобы понять когда вернуть статус конфликт. Но возможно правильнее было реализовать эту логику в репозитории, но тут я сомневался

2023-11-22 13:40 UTC, DenisKhanov commented on internal/app/handlers/handlers.go
> +		c.Status(http.StatusBadRequest)
Согласен, меня это тоже удивило, что везде кидаем бед реквесты, но таково условие задания)

2023-11-22 13:43 UTC, DenisKhanov commented on internal/app/handlers/handlers.go
> +		if err := h.DB.Ping(context.Background()); err != nil {
Точно, упустил этот метод👍

2023-11-22 13:46 UTC, DenisKhanov commented on internal/app/handlers/handlers.go
> +		c.Status(http.StatusOK)
Точно, добавил и сюда  c.Status(http.StatusInternalServerError)

2023-11-22 13:48 UTC, DenisKhanov commented on internal/app/repositoryes/dbstore.go
My english is bad, спасибо!)

2023-11-22 13:52 UTC, DenisKhanov commented on internal/app/repositoryes/dbstore.go
> +		logrus.Panicf("don't create table shortedurl: %v", err)
Изменил👌

2023-11-22 13:53 UTC, DenisKhanov commented on internal/app/repositoryes/dbstore.go
> +	fmt.Println(2)
Да😊🙈

2023-11-22 14:03 UTC, DenisKhanov commented on internal/app/repositoryes/repository.go
> +	saveCtx, cancel := context.WithTimeout(context.Background(), time.Minute)
Ну я подумал, что в случае отмены запроса пользоваетелем мне не стоит грузить базу, а вот хранение в оперативе все равно осуществлю, так как в плане скорости оно не стоит ничего.

2023-11-22 14:04 UTC, DenisKhanov commented on internal/app/repositoryes/repository.go
> +			fmt.Println("Error saving to memory")
Да, упустил этот момент

2023-11-22 14:04 UTC, DenisKhanov commented on internal/app/services/service.go
> +	fmt.Println("Service GetBatchJSONShortURL run")
😊🙈

2023-11-22 14:10 UTC, DenisKhanov commented on internal/app/services/service.go
> +			batchURLResponses = append(batchURLResponses, models.URLResponse{CorrelationID: value.CorrelationID, ShortURL: s.baseURL + "/" + shortURL})
Точно, как раз думал как избавиться от этого мусора👍

2023-11-22 14:17 UTC, DenisKhanov commented on internal/app/services/service.go
> +	saveCtx, cancel := context.WithTimeout(context.Background(), time.Minute)
Я тут переопределил контекст для того, чтобы если за минуту не произойдет запись списка урлов в базу, то прервать ее.  Думаешь лучше ее тоже прерывать при отмене запроса от пользователя?