Iter5
DenisKhanov/shorterURL pull request #5
Opened 2023-10-12 16:42 UTC by DenisKhanov

Выполнен 5 инкремент

2023-10-15 23:54 UTC, DenisKhanov commented
На ночь глядя с тестированием репозитория дичь какую-то сделал, потом перепишу)

2023-10-16 06:43 UTC, edylcrm requested changes

2023-10-16 06:43 UTC, edylcrm commented on cmd/shortener/client/main.go
> +package main
Комментарии разделены на несколько типов:
[BLOCKER] - Проблема, не решив которую принять работу нельзя
[LINT] - Заменичение, опционально к выполнению.
[FYI] - просто ремарка

2023-10-16 06:43 UTC, edylcrm commented on cmd/shortener/main.go
> +		panic(err)
[FYI] Здесь так же было бы хорошо слушать сигналы ОС и корректно завершать http сервис чтобы пользователи в момент редеплоя приложения или принудительного завершения получили ответ.
Пример работы с сигналами: https://gobyexample.com/signals
Как корректно завершать http сервис: https://pkg.go.dev/net/http#Server.SetKeepAlivesEnabled и https://pkg.go.dev/net/http#Server.Shutdown

2023-10-16 06:43 UTC, edylcrm commented on internal/app/repositoryes/repository.go
> +		id:             id,
**[BLOCKER]** Не совсем понятно почему id должен передаваться в конструктор, почему нельзя инициализировать его самому объекту который он нужен?

2023-10-16 06:43 UTC, edylcrm commented on internal/app/repositoryes/repository.go
> +func (d *RepositoryURL) GetOriginalURLFromDB(shortURL string) (string, bool) {
**[LINT]** В следующих спринтах будут добавляться новые виды хранились. Я бы к этому подготовился и чуть-чуть поменял контракт на:
```
GetOriginalURLFromDB(shortURL string) (string, error)
GetShortURLFromDB(originalURL string) (string, error)
```

2023-10-16 06:43 UTC, edylcrm commented on internal/app/repositoryes/repository.go
> +func (d *RepositoryURL) GetIDFromDB() int {
**[BLOCKER]** Если этот метод нужен для генерации shortURL и вся логика по генерации находится в service, может тогда стоит и этот метод унести в service?

2023-10-16 17:17 UTC, DenisKhanov commented on internal/app/repositoryes/repository.go
> +func (d *RepositoryURL) GetIDFromDB() int {
Но ведь тогда мне нужно будет сделать поле id структуры репозитория глобальным что даст к нему доступ из вне, хорошо ли это?

2023-10-17 07:43 UTC, edylcrm commented on internal/app/services/service.go
> +		panic(err)
**[LINT]** В бизнес логики лучше никогда не кидать panic, а возвращать ошибку. Panic завершает приложение и если что-то пойдет не так на проде, то приложение может упасть и заново не подняться.
Я возвращать на доработку не буду, поправь как будет время.

2023-10-17 07:43 UTC, edylcrm approved these changes

2023-10-18 20:21 UTC, merged

2023-10-18 20:21 UTC, DenisKhanov commented
Выполнен первый спринт с дополнением в виде прослушивания сигналов